using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.Extensions.Logging;
using NuGet.Frameworks;
using Stryker.Abstractions;
using Stryker.Abstractions.Analysis;
using Stryker.Abstractions.Exceptions;
using Stryker.Utilities.EmbeddedResources;

namespace Stryker.Utilities.MSBuild;

/// <summary>
/// Extension helpers that operate on <see cref="IProjectAnalysis"/> — the
/// stryker-netx replacement for <c>Buildalyzer.IAnalyzerResult</c>. Each method
/// preserves the semantics of the corresponding extension on <c>IAnalyzerResult</c>
/// so that callers can be migrated 1:1 in Phase 9b.
/// </summary>
public static partial class IProjectAnalysisExtensions
{
    /// <summary>
    /// Returns the project's compiled assembly file name (e.g. <c>Sample.Library.dll</c>),
    /// normalized for the current platform's directory separators.
    /// </summary>
    public static string GetAssemblyFileName(this IProjectAnalysis projectAnalysis) =>
        FilePathUtils.NormalizePathSeparators(projectAnalysis.TargetFileName)!;

    /// <summary>
    /// True when the project produces an assembly (i.e. has a non-empty <c>TargetFileName</c>).
    /// </summary>
    public static bool BuildsAnAssembly(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.BuildsAnAssembly;

    /// <summary>
    /// Returns the path of the project's reference-assembly variant
    /// (<c>obj/.../ref/...dll</c>) when present; otherwise the regular assembly path.
    /// </summary>
    public static string GetReferenceAssemblyPath(this IProjectAnalysis projectAnalysis)
    {
        var refPath = projectAnalysis.OutputRefFilePath;
        return string.IsNullOrEmpty(refPath)
            ? projectAnalysis.GetAssemblyPath()
            : FilePathUtils.NormalizePathSeparators(refPath)!;
    }

    /// <summary>
    /// Returns the directory that contains the compiled assembly
    /// (e.g. <c>bin/Debug/net10.0/</c>), normalized for the current platform.
    /// </summary>
    public static string GetAssemblyDirectoryPath(this IProjectAnalysis projectAnalysis) =>
        FilePathUtils.NormalizePathSeparators(projectAnalysis.TargetDir)!;

    /// <summary>
    /// Returns the absolute path of the compiled assembly, normalized for the current platform.
    /// </summary>
    public static string GetAssemblyPath(this IProjectAnalysis projectAnalysis) =>
        FilePathUtils.NormalizePathSeparators(Path.Combine(projectAnalysis.GetAssemblyDirectoryPath(),
            projectAnalysis.GetAssemblyFileName()))!;

    /// <summary>
    /// Returns the project's <c>AssemblyName</c> property value, normalized for the current platform.
    /// </summary>
    public static string GetAssemblyName(this IProjectAnalysis projectAnalysis) =>
        FilePathUtils.NormalizePathSeparators(projectAnalysis.AssemblyName)!;

    /// <summary>
    /// Loads the embedded resources declared by the project as Roslyn
    /// <see cref="ResourceDescription"/> instances, ready to be passed to a
    /// <c>CSharpCompilation</c>. Resource paths are produced relative to the
    /// project directory because <c>EmbeddedResourcesGenerator.GenerateManifestResources</c>
    /// expects relative includes in order to compose the resource manifest name correctly.
    /// </summary>
    public static IEnumerable<ResourceDescription> GetResources(this IProjectAnalysis projectAnalysis, ILogger logger)
    {
        ArgumentNullException.ThrowIfNull(projectAnalysis);
        var rootNamespace = projectAnalysis.GetRootNamespace();
        var projectDir = string.IsNullOrEmpty(projectAnalysis.ProjectFilePath)
            ? string.Empty
            : Path.GetDirectoryName(projectAnalysis.ProjectFilePath) ?? string.Empty;

        var embeddedResources = projectAnalysis.GetItemPaths("EmbeddedResource")
            .Select(path => string.IsNullOrEmpty(projectDir) || !Path.IsPathRooted(path)
                ? path
                : Path.GetRelativePath(projectDir, path));

        return EmbeddedResourcesGenerator.GetManifestResources(
            projectAnalysis.GetAssemblyPath(),
            projectAnalysis.ProjectFilePath,
            rootNamespace,
            embeddedResources);
    }

    /// <summary>
    /// Returns the file name of the assembly-info source generated by the SDK
    /// (<c>obj/.../&lt;projectName&gt;.AssemblyInfo.cs</c> by default).
    /// </summary>
    public static string AssemblyAttributeFileName(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetPropertyOrDefault("GeneratedAssemblyInfoFile",
            (Path.GetFileNameWithoutExtension(projectAnalysis.ProjectFilePath) + ".AssemblyInfo.cs")
            .ToLowerInvariant())!;

    /// <summary>
    /// Returns the expected PDB symbol file name for the project's assembly
    /// (<c>&lt;AssemblyName&gt;.pdb</c>).
    /// </summary>
    public static string GetSymbolFileName(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.AssemblyName + ".pdb";

    /// <summary>
    /// Returns the project's <c>TargetPlatform</c> MSBuild property; defaults to <c>AnyCPU</c>.
    /// </summary>
    public static string TargetPlatform(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetPropertyOrDefault("TargetPlatform", "AnyCPU")!;

    /// <summary>
    /// Always returns <c>null</c>; the MSBuild executable path is now managed by
    /// <c>Microsoft.Build.Locator</c> which resolves the SDK MSBuild at startup, so
    /// individual project analyses no longer carry a per-project MsBuild path.
    /// </summary>
    public static string? MsBuildPath(this IProjectAnalysis projectAnalysis)
    {
        // MSBuildLocator-managed: the workspace is bootstrapped against the SDK MSBuild
        // before any project is loaded, so there is no per-project MsBuildExePath to surface.
        _ = projectAnalysis;
        return null;
    }

    /// <summary>
    /// Loads C# source generators from the project's analyzer references.
    /// </summary>
    public static IEnumerable<ISourceGenerator> GetSourceGenerators(this IProjectAnalysis projectAnalysis, ILogger logger)
    {
        ArgumentNullException.ThrowIfNull(projectAnalysis);
        ArgumentNullException.ThrowIfNull(logger);

        var generators = new List<ISourceGenerator>();
        foreach (var analyzer in projectAnalysis.AnalyzerAssemblyPaths)
        {
            try
            {
                var analyzerFileReference = new AnalyzerFileReference(analyzer, AnalyzerAssemblyLoader.Instance);
                analyzerFileReference.AnalyzerLoadFailed += (sender, e) => LogAnalyzerLoadError(logger, sender, e);
                generators.AddRange(analyzerFileReference.GetGenerators(LanguageNames.CSharp));
            }
            catch (Exception e) when (e is not OperationCanceledException)
            {
                LogAnalyzerLoadWarning(logger, e, analyzer);
            }
        }

        return generators;
    }

    [ExcludeFromCodeCoverage(Justification = "Impossible to unit test")]
    private static void LogAnalyzerLoadError(ILogger? logger, object? sender, AnalyzerLoadFailureEventArgs e)
    {
        if (logger is null)
        {
            return;
        }

        var source = (sender as AnalyzerReference)?.Display ?? "unknown";
        LogAnalyzerLoadFailed(
            logger,
            source,
            e.Message,
            Enum.GetName(e.ErrorCode.GetType(), e.ErrorCode) ?? e.ErrorCode.ToString(),
            e.TypeName ?? "All");
        if (e.ErrorCode == AnalyzerLoadFailureEventArgs.FailureErrorCode.ReferencesNewerCompiler)
        {
            LogAnalyzerNewerCompiler(logger, source, e.ReferencedCompilerVersion);
        }

        if (e.Exception != null)
        {
            LogAnalyzerLoadException(logger, e.Exception, source);
        }
    }

    [LoggerMessage(Level = LogLevel.Warning, Message = "Analyzer/Generator assembly {Analyzer} could not be loaded.\nGenerated source code may be missing.")]
    private static partial void LogAnalyzerLoadWarning(ILogger logger, Exception ex, string analyzer);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Failed to load analyzer '{Source}': {Message} (error : {Error}, analyzer: {Analyzer}).")]
    private static partial void LogAnalyzerLoadFailed(ILogger logger, string source, string message, string error, string analyzer);

    [LoggerMessage(Level = LogLevel.Warning, Message = "The analyzer '{Source}' references a newer version ({ReferencedCompilerVersion}) of the compiler than the one used by Stryker.NET.")]
    private static partial void LogAnalyzerNewerCompiler(ILogger logger, string source, Version? referencedCompilerVersion);

    [LoggerMessage(Level = LogLevel.Warning, Message = "Failed to load analyzer '{Source}'.")]
    private static partial void LogAnalyzerLoadException(ILogger logger, Exception ex, string source);

    /// <summary>
    /// Materialises the project's metadata references as Roslyn
    /// <see cref="MetadataReference"/> instances, applying any reference aliases.
    /// </summary>
    public static IEnumerable<MetadataReference> LoadReferences(this IProjectAnalysis projectAnalysis)
    {
        ArgumentNullException.ThrowIfNull(projectAnalysis);
        return LoadReferencesIterator(projectAnalysis);
    }

    private static IEnumerable<MetadataReference> LoadReferencesIterator(IProjectAnalysis projectAnalysis)
    {
        foreach (var reference in projectAnalysis.References)
        {
            if (!projectAnalysis.ReferenceAliases.TryGetValue(reference, out var aliases) || aliases is null)
            {
                aliases = [];
            }

            yield return MetadataReference.CreateFromFile(reference).WithAliases([.. aliases]);
        }
    }

    /// <summary>
    /// Parses the project's <c>TargetFramework</c> moniker as a <see cref="NuGetFramework"/>.
    /// Throws <see cref="InputException"/> when the moniker is not recognised.
    /// </summary>
    public static NuGetFramework? GetNuGetFramework(this IProjectAnalysis projectAnalysis)
    {
        ArgumentNullException.ThrowIfNull(projectAnalysis);

        if (string.IsNullOrEmpty(projectAnalysis.TargetFramework))
        {
            return null;
        }
        var framework = NuGetFramework.Parse(projectAnalysis.TargetFramework);
        if (framework != NuGetFramework.UnsupportedFramework)
        {
            return framework;
        }

        var atPath = string.IsNullOrEmpty(projectAnalysis.ProjectFilePath)
            ? ""
            : $" at '{projectAnalysis.ProjectFilePath}'";
        var message =
            $"The target framework '{projectAnalysis.TargetFramework}' is not supported. Please fix the target framework in the csproj{atPath}.";
        throw new InputException(message);
    }

    /// <summary>
    /// True when the project targets the legacy desktop .NET Framework (e.g. <c>net48</c>).
    /// </summary>
    public static bool TargetsFullFramework(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetNuGetFramework()?.IsDesktop() == true;

    /// <summary>
    /// Returns the Roslyn <see cref="Language"/> the project is written in.
    /// </summary>
    public static Language GetLanguage(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetPropertyOrDefault("Language") switch
        {
            "F#" => Language.Fsharp,
            "C#" => Language.Csharp,
            _ => Language.Undefined,
        };

    /// <summary>
    /// True when the analysis contains enough information to be usable for mutation testing.
    /// Mirrors the heuristic from the Buildalyzer-era extension.
    /// </summary>
    public static bool IsValid(this IProjectAnalysis projectAnalysis)
    {
        ArgumentNullException.ThrowIfNull(projectAnalysis);

        return projectAnalysis.Succeeded
            || (projectAnalysis.SourceFiles.Count > 0 && projectAnalysis.References.Count > 0)
            || (projectAnalysis.IsTestProject
                && !string.IsNullOrEmpty(projectAnalysis.TargetDir)
                && projectAnalysis.ProjectReferences.Any());
    }

    /// <summary>
    /// True when the analysis is valid and targets the requested <paramref name="framework"/>.
    /// </summary>
    public static bool IsValidFor(this IProjectAnalysis projectAnalysis, string framework) =>
        projectAnalysis.IsValid() && string.Equals(projectAnalysis.TargetFramework, framework, StringComparison.Ordinal);

    /// <summary>
    /// True when at least one of the supplied analyses is detected as a test project.
    /// </summary>
    public static bool IsTestProject(this IEnumerable<IProjectAnalysis> projectAnalyses)
    {
        ArgumentNullException.ThrowIfNull(projectAnalyses);
        return projectAnalyses.Any(x => x.IsTestProject);
    }

    /// <summary>
    /// Maps the project's <c>OutputType</c> MSBuild property to the corresponding
    /// Roslyn <see cref="OutputKind"/>.
    /// </summary>
    public static OutputKind GetOutputKind(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetPropertyOrDefault("OutputType") switch
        {
            "Exe" => OutputKind.ConsoleApplication,
            "WinExe" => OutputKind.WindowsApplication,
            "Module" => OutputKind.NetModule,
            "AppContainerExe" => OutputKind.WindowsRuntimeApplication,
            "WinMdObj" => OutputKind.WindowsRuntimeMetadata,
            _ => OutputKind.DynamicallyLinkedLibrary
        };

    /// <summary>
    /// Returns the project's <c>CompilerAPIVersion</c> MSBuild property; defaults to <c>Unknown</c>.
    /// </summary>
    public static string GetCompilerApiVersion(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetPropertyOrDefault("CompilerAPIVersion", "Unknown")!;

    /// <summary>
    /// True when the project produces a strong-named assembly (<c>SignAssembly</c> set).
    /// </summary>
    public static bool IsSignedAssembly(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetPropertyOrDefault("SignAssembly", false);

    /// <summary>
    /// True when the project requests a delay-signed assembly (<c>DelaySign</c> set).
    /// </summary>
    public static bool IsDelayedSignedAssembly(this IProjectAnalysis projectAnalysis) =>
        projectAnalysis.GetPropertyOrDefault("DelaySign", false);

    /// <summary>
    /// Returns the absolute path of the project's strong-name key file
    /// (<c>AssemblyOriginatorKeyFile</c>), or <c>null</c> when none is configured.
    /// </summary>
    public static string? GetAssemblyOriginatorKeyFile(this IProjectAnalysis projectAnalysis)
    {
        var assemblyKeyFileProp = projectAnalysis.GetPropertyOrDefault("AssemblyOriginatorKeyFile");
        return string.IsNullOrEmpty(assemblyKeyFileProp)
            ? null
            : Path.Combine(Path.GetDirectoryName(projectAnalysis.ProjectFilePath) ?? ".", assemblyKeyFileProp);
    }

    /// <summary>
    /// Aggregates the project's diagnostic options (<c>NoWarn</c>, <c>WarningsAsErrors</c>,
    /// <c>WarningsNotAsErrors</c>) into a single map suitable for Roslyn's
    /// <c>CompilationOptions.SpecificDiagnosticOptions</c>.
    /// </summary>
    public static ImmutableDictionary<string, ReportDiagnostic> GetDiagnosticOptions(
        this IProjectAnalysis projectAnalysis)
    {
        var noWarnString = projectAnalysis.GetPropertyOrDefault("NoWarn");
        var noWarn = ParseDiagnostics(noWarnString).ToDictionary(x => x, _ => ReportDiagnostic.Suppress, StringComparer.Ordinal);

        var warningsAsErrorsString = projectAnalysis.GetPropertyOrDefault("WarningsAsErrors");
        var warningsAsErrors = ParseDiagnostics(warningsAsErrorsString).ToDictionary(x => x, _ => ReportDiagnostic.Error, StringComparer.Ordinal);

        var warningsNotAsErrorsString = projectAnalysis.GetPropertyOrDefault("WarningsNotAsErrors");
        var warningsNotAsErrors = ParseDiagnostics(warningsNotAsErrorsString).ToDictionary(x => x, _ => ReportDiagnostic.Warn, StringComparer.Ordinal);

        // merge settings,
        var diagnosticOptions = new Dictionary<string, ReportDiagnostic>(warningsAsErrors, StringComparer.Ordinal);
        foreach (var item in warningsNotAsErrors)
        {
            diagnosticOptions[item.Key] = item.Value;
        }

        foreach (var item in noWarn)
        {
            diagnosticOptions[item.Key] = item.Value;
        }

        return diagnosticOptions.ToImmutableDictionary(StringComparer.Ordinal);
    }

    private static IEnumerable<string> ParseDiagnostics(string? diagnostics)
    {
        if (string.IsNullOrWhiteSpace(diagnostics))
        {
            return [];
        }

        return diagnostics
            .Split(";")
            .Select(x => x.Trim('\r', '\n', ' '))
            .Distinct(StringComparer.Ordinal)
            .Where(x => !string.IsNullOrWhiteSpace(x));
    }

    /// <summary>
    /// Returns the project's <c>WarningLevel</c> MSBuild property as an integer; defaults to <c>4</c>.
    /// </summary>
    public static int GetWarningLevel(this IProjectAnalysis projectAnalysis) =>
        int.Parse(projectAnalysis.GetPropertyOrDefault("WarningLevel", "4")!, CultureInfo.InvariantCulture);

    private static string GetRootNamespace(this IProjectAnalysis projectAnalysis)
    {
        var rootNamespace = projectAnalysis.GetPropertyOrDefault("RootNamespace");
        return string.IsNullOrEmpty(rootNamespace)
            ? projectAnalysis.GetAssemblyName()
            : rootNamespace;
    }

    /// <summary>
    /// Boolean overload of <see cref="IProjectAnalysis.GetPropertyOrDefault(string, string)"/>:
    /// returns <paramref name="defaultBoolean"/> when the property is missing/empty,
    /// otherwise parses the value with <see cref="bool.Parse(string)"/>.
    /// </summary>
    public static bool GetPropertyOrDefault(this IProjectAnalysis projectAnalysis, string name, bool defaultBoolean)
    {
        ArgumentNullException.ThrowIfNull(projectAnalysis);
        var value = projectAnalysis.GetPropertyOrDefault(name);
        return string.IsNullOrEmpty(value) ? defaultBoolean : bool.Parse(value);
    }

    private sealed class AnalyzerAssemblyLoader : IAnalyzerAssemblyLoader
    {
        public static readonly IAnalyzerAssemblyLoader Instance = new AnalyzerAssemblyLoader();

        private readonly Dictionary<string, Assembly> _cache = [];

        private AnalyzerAssemblyLoader() { }

        public void AddDependencyLocation(string fullPath)
        {
            if (!_cache.ContainsKey(fullPath))
            {
                _cache[fullPath] = SafeLoadFrom(fullPath);
            }
        }

        public Assembly LoadFromPath(string fullPath)
        {
            if (!_cache.TryGetValue(fullPath, out var assembly))
            {
                _cache[fullPath] = assembly = SafeLoadFrom(fullPath);
            }
            return assembly;
        }

        [ExcludeFromCodeCoverage(Justification = "Impossible to unit test")]
        private static Assembly SafeLoadFrom(string fullPath)
        {
            try
            {
                // Stryker plugin loader needs to load assemblies from a specific file path
                // (e.g., user-supplied analyzer DLLs). Assembly.Load(name) cannot satisfy this
                // contract because it resolves by AssemblyName, not by file path.
#pragma warning disable S3885 // Assembly.LoadFrom is required for plugin/analyzer loading by path
                return Assembly.LoadFrom(fullPath);
#pragma warning restore S3885
            }
            catch (FileLoadException)
            {
                // This can happen if the assembly has already been loaded: CLR refuses to load the same
                // assembly from two different paths. In that case, we try to find the already loaded assembly.
                // if we fail, we simply rethrow the original exception
                var assemblyName = AssemblyName.GetAssemblyName(fullPath);
                // find already loaded assembly
                var loadedAssembly = AppDomain.CurrentDomain.GetAssemblies()
                    .FirstOrDefault(a => AssemblyName.ReferenceMatchesDefinition(a.GetName(), assemblyName));
                if (loadedAssembly != null)
                {
                    return loadedAssembly;
                }

                throw;
            }
        }
    }
}
